version: '3'
services:
  validator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bt2c_validator
    restart: always
    ports:
      - "8334:8334"
      - "9092:9092"
      - "3000:3000"
      - "8081:8081"
    volumes:
      - ./config:/app/config
      - bt2c_blockchain_data:/app/data
    environment:
      - NODE_NAME=developer_node
      - WALLET_ADDRESS=bt2c_4k3qn2qmiwjeqkhf44wtowxb
      - STAKE_AMOUNT=1001.0
      - LOG_LEVEL=info
    command: python run_validator.py
  
  prometheus:
    image: prom/prometheus:latest
    container_name: bt2c_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - bt2c_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
  
  grafana:
    image: grafana/grafana:latest
    container_name: bt2c_grafana
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - bt2c_grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  bt2c_blockchain_data:
    driver: local
  bt2c_prometheus_data:
    driver: local
  bt2c_grafana_data:
    driver: local
