version: '3.8'

services:
  validator:
    build:
      context: ./context
      dockerfile: ../Dockerfile
    container_name: bt2c-validator-validator1
    volumes:
      - ./context:/app/context
      - ./data:/data
      - ./certs:/certs
      - ./config:/config
    ports:
      - "8000:8000"
      - "26656:26656"
    environment:
      - NODE_ID=validator1
      - NETWORK=mainnet
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: bt2c-postgres-validator1
    environment:
      - POSTGRES_DB=bt2c
      - POSTGRES_USER=bt2c
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bt2c"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bt2c-redis-validator1
    volumes:
      - ./data/redis:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: bt2c-prometheus-validator1
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: bt2c-grafana-validator1
    volumes:
      - ./metrics/grafana:/var/lib/grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_password

networks:
  default:
    name: bt2c_validator1_network