{
  "global": {
    "scrape_interval": "15s",
    "evaluation_interval": "15s"
  },
  "rule_files": [
    "rules/*.yml"
  ],
  "scrape_configs": [
    {
      "job_name": "bt2c_validators",
      "static_configs": [
        {
          "targets": [
            "localhost:8000"
          ]
        }
      ],
      "metrics_path": "/metrics"
    }
  ],
  "alerting": {
    "alertmanagers": [
      {
        "static_configs": [
          {
            "targets": [
              "localhost:9093"
            ]
          }
        ]
      }
    ]
  }
}