global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bt2c'
    static_configs:
      - targets: ['validator-1:8000', 'validator-2:8000', 'validator-3:8000', 'validator-4:8000', 'validator-5:8000']
