{
  "version": "3.8",
  "services": {
    "prometheus": {
      "image": "prom/prometheus:latest",
      "volumes": [
        "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml",
        "./prometheus/rules:/etc/prometheus/rules"
      ],
      "ports": [
        "9091:9090"
      ],
      "command": [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.retention.time=15d"
      ]
    },
    "grafana": {
      "image": "grafana/grafana:latest",
      "volumes": [
        "./grafana/provisioning:/etc/grafana/provisioning",
        "./grafana/dashboards:/etc/grafana/dashboards"
      ],
      "ports": [
        "3001:3000"
      ],
      "environment": [
        "GF_SECURITY_ADMIN_PASSWORD=secure_password"
      ]
    },
    "alertmanager": {
      "image": "prom/alertmanager:latest",
      "volumes": [
        "./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      ],
      "ports": [
        "9093:9093"
      ],
      "command": [
        "--config.file=/etc/alertmanager/alertmanager.yml"
      ]
    }
  }
}