global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bt2c_validator'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['validator:8000']
    metrics_path: '/metrics'
