{
  "global": {
    "scrape_interval": "15s",
    "evaluation_interval": "15s"
  },
  "scrape_configs": [
    {
      "job_name": "validator",
      "static_configs": [
        {
          "targets": [
            "validator:8000"
          ]
        }
      ],
      "scheme": "https",
      "tls_config": {
        "insecure_skip_verify": true
      }
    },
    {
      "job_name": "node",
      "static_configs": [
        {
          "targets": [
            "validator:26656"
          ]
        }
      ],
      "scheme": "https",
      "tls_config": {
        "insecure_skip_verify": true
      }
    }
  ]
}