global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'seed1'
    static_configs:
      - targets: ['seed1:26660']
    metrics_path: '/metrics'

  - job_name: 'seed2'
    static_configs:
      - targets: ['seed2:26661']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
